// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igqpbfjlajymryajrzfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncXBiZmpsYWp5bXJ5YWpyemZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNDk3NDksImV4cCI6MjA1NDgyNTc0OX0.vStIxOmryTc4Mkl2HxTPQPZq7SvWN2zUzBK9QTeQ3PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);